version: '1'
name: automated_triage_setup
description: setup state for automated triage
enabled: true
tags:
- automated_observability_triage
triggers:
- type: manual
  enabled: true
consts:
  ai_connector: TBD
  ai_proxy: TBD
  ai_timeout: 10m
  es_host: TBD
  kbn_auth: TBD
  kbn_host: TBD
  snow_host: TBD
  snow_auth: TBD
steps:

- name: create_pipeline
  type: http
  with:
    url: '{{ consts.es_host }}/_ingest/pipeline/add_timestamp_pipeline'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      description: Adds a timestamp to documents
      processors:
      - set:
          field: '@timestamp'
          value: '{% raw %}{{ _ingest.timestamp }}{% endraw %}'
    timeout: 30s
  on-failure:
    continue: true

- name: delete_alert_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_alert_queue'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_alert_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_alert_queue'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      settings:
        index.default_pipeline: add_timestamp_pipeline
      mappings:
        properties:
          alert:
            type: flattened
          '@timestamp':
            type: date
    timeout: 30s
- name: delete_case_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_case_queue'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_case_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_case_queue'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      settings:
        index.default_pipeline: add_timestamp_pipeline
      mappings:
        properties:
          case_id:
            type: keyword
          '@timestamp':
            type: date
    timeout: 30s

- name: setup_cases
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/cases/configure'
    method: POST
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    body:
      closure_type: close-by-user
      connector:
        fields:
        id: none
        name: none
        type: .none
      customFields:
      - defaultValue: not_available
        key: system
        label: system
        required: false
        type: text
      - defaultValue: not_available
        key: ai_conversation_id
        label: ai_conversation_id
        required: false
        type: text

      - defaultValue: not_available
        key: service
        label: service
        required: false
        type: text

      - defaultValue: not_available
        key: cmdb_owner
        label: cmdb_owner
        required: false
        type: text

      - defaultValue: not_available
        key: cmdb_support_group
        label: cmdb_support_group
        required: false
        type: text

      - defaultValue: not_available
        key: cmdb_id
        label: cmdb_id
        required: false
        type: text

      owner: observability
    timeout: 30s
  on-failure:
    continue: true

- name: get_connectors
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/actions/connectors'
    method: GET
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana

- name: foreach_connector
  type: foreach
  foreach: '{{ steps.get_connectors.output.data | json }}'
  steps:
  - name: is_snow
    type: if
    condition: 'foreach.item.connector_type_id : .servicenow'
    steps:
    - name: setup_cases2
      type: http
      with:
        url: '{{ consts.kbn_host }}/api/cases/configure/{{steps.setup_cases.output.data.id}}'
        method: PATCH
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        body:
          version: '{{ steps.setup_cases.output.data.version}}'
          connector:
            fields:
            id: '{{ foreach.item.id }}'
            name: '{{ foreach.item.name }}'
            type: '{{ foreach.item.connector_type_id }}'
        timeout: 30s
      on-failure:
        continue: true

- name: delete_topology
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_topology'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_topology
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_topology'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      settings:
        index.default_pipeline: add_timestamp_pipeline
      mappings:
        properties:
          '@timestamp':
            type: date
          system:
            type: keyword
          topology:
            type: flattened
    timeout: 30s
  on-failure:
    continue: true

- name: delete_cmdb
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_cmdb'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_cmdb
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_cmdb'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      settings:
        index.default_pipeline: add_timestamp_pipeline
      mappings:
        properties:
          '@timestamp':
            type: date
          service.environment:
            type: keyword
          service.name:
            type: keyword
          cmdb_id:
            type: keyword
          cmdb_owner:
            type: keyword
          cmdb_support_group:
            type: keyword
    timeout: 30s
  on-failure:
    continue: true

- name: delete_config
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_config
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      settings:
        index.mode: lookup
      mappings:
        properties:
          workflowId:
            type: keyword
          id:
            type: keyword
          name:
            type: keyword
    timeout: 30s
- name: get_workflows
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/workflows/search'
    method: POST
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    body:
      limit: 20
      page: 1
      query: ''
    timeout: 30s
- name: foreach_workflow
  type: foreach
  foreach: '{{ steps.get_workflows.output.data.results | json }}'
  steps:
  - name: save_id
    type: http
    with:
      url: '{{ consts.es_host }}/workflow_config/_doc/{{ foreach.item.name }}'
      method: POST
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      body:
        workflowId: '{{ foreach.item.id }}'
        id: '{{ foreach.item.id }}'
        name: '{{ foreach.item.name }}'
      timeout: 30s

