name: case_dequeue
description: dequeue cases serially and start processing
enabled: true
tags:
- automated_observability_triage
triggers:
- type: scheduled
  with:
    every: 30s
consts:
  ai_connector: TBD
  ai_proxy: TBD
  ai_timeout: 10m
  es_host: TBD
  kbn_auth: TBD
  kbn_host: TBD
  snow_host: TBD
  snow_auth: TBD
steps:
- name: get_case_process_id
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config/_doc/case_process'
    method: GET
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    timeout: 30s
- name: case_process_status
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_case_process_id.output.data._source.workflowId}}'
    method: GET
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    timeout: 30s

- name: get_alert_process_id
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: GET
    timeout: 30s
    url: '{{ consts.es_host }}/workflow_config/_doc/alert_process'
- name: alert_process_status
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: GET
    url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_alert_process_id.output.data._source.workflowId }}'

- name: is_alert_process_running
  type: if
  condition: 'steps.alert_process_status.output.data.results[0].status : running'
  steps:
  - name: is_alert_process_running_debug1
    type: console
    with:
      message: workflow_alert_process running
  else:
  - name: is_alert_process_running_debug2
    type: console
    with:
      message: workflow_alert_process not running

  - name: is_case_process_running
    type: if
    condition: 'steps.case_process_status.output.data.results[0].status : running'
    steps:
    - name: is_case_process_running_debug1
      type: console
      with:
        message: workflow_case_process running
    else:
    - name: is_case_process_running_debug2
      type: console
      with:
        message: workflow_case_process not running
    - name: dequeue_case
      type: http
      with:
        url: '{{ consts.es_host }}/workflow_case_queue/_search'
        method: POST
        body:
          _source: true
          query:
            match_all: {}
          size: 1
          sort:
          - '@timestamp':
              order: asc
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
    - name: is_case_pending
      type: if
      condition: steps.dequeue_case.output.data.hits.total.value > 0
      steps:

      - name: is_case_stable
        type: if
        condition: steps.dequeue_case.output.data.hits.hits[0]._source.@timestamp < now-15s
        steps:
        - name: mark_case_handled
          type: http
          with:
            url: '{{ consts.es_host }}/workflow_case_queue/_delete_by_query'
            method: POST
            body:
              query:
                match:
                  case_id: '{{ steps.dequeue_case.output.data.hits.hits[0]._source.case_id }}'
            headers:
              Authorization: '{{ consts.kbn_auth }}'
              Content-Type: application/json

        - name: start_case_process
          type: http
          with:
            url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflowId}}/run'
            method: POST
            headers:
              Authorization: '{{ consts.kbn_auth }}'
              Content-Type: application/json
              kbn-xsrf: true
              x-elastic-internal-origin: kibana
            body: '{ "inputs": {"case_id": "{{ steps.dequeue_case.output.data.hits.hits[0]._source.case_id }}" } }'
            timeout: 30s




