consts:
  ai_connector: TBD
  ai_proxy: TBD
  ai_timeout: 10m
  es_host: TBD
  kbn_auth: TBD
  kbn_host: TBD
  topology_lookback_time: 1h
  snow_host: https://dev197057.service-now.com
  snow_auth: Basic YWRtaW46Tmk4bmZRREcqOGVA
name: topology
enabled: true
version: '1'
description: build topology to help with correlation and RCA
tags:
- automated_observability_triage
settings:
  timeout: 20m
triggers:
- type: manual
- enabled: true
  type: scheduled
  with:
    every: 1h
steps:
- name: get_end_time
  type: http
  with:
    body:
      query: ROW current_date = NOW()
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: POST
    url: '{{ consts.es_host }}/_query'
- name: get_start_time
  type: http
  with:
    body:
      query: ROW current_date = NOW() - {{ consts.topology_lookback_time }}
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: POST
    url: '{{ consts.es_host }}/_query'

- name: get_service_environments
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: GET
    url: '{{ consts.kbn_host }}/internal/apm/environments?start={{ steps.get_start_time.output.data.values[0] }}&end={{ steps.get_end_time.output.data.values[0] }}'

- name: foreach_environment
  type: foreach
  foreach: '{{ steps.get_service_environments.output.data.environments | json }}'
  steps:

  - name: get_service_map
    type: http
    with:
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
        kbn-xsrf: true
        x-elastic-internal-origin: kibana
      method: GET
      url: '{{ consts.kbn_host }}/internal/apm/service-map?start={{ steps.get_start_time.output.data.values[0] }}&end={{ steps.get_end_time.output.data.values[0] }}&environment={{ foreach.item }}&serviceGroup=&kuery='

  - name: foreach_span
    type: foreach
    foreach: '{{ steps.get_service_map.output.data.servicesData | json }}'
    steps:
    - name: debug
      type: console
      with:
        message: "{{ foreach.item['service.name']}}"

    - name: get_snow_service
      type: http
      with:
        headers:
          Authorization: '{{ consts.snow_auth }}'
          Accept: application/json
        method: GET
        url: "{{ consts.snow_host }}/api/now/cmdb/csdm/app_service/find_service?name={{ foreach.item['service.name']}}"
      on-failure:
        continue: true

    - name: create_snow_service
      type: if
      condition: 'not steps.get_snow_service.output.data.result.services[0].number : *'
      steps:
          # create snow services
      - name: update_snow_service
        type: http
        with:
          headers:
            Authorization: '{{ consts.snow_auth }}'
            Accept: application/json
          method: POST
          url: '{{ consts.snow_host }}/api/now/cmdb/csdm/app_service/register_service'
          body:
            basic_details:
              environemnt: Production
              name: "{{ foreach.item['service.name']}}"
              version: '1.0'
        on-failure:
          continue: true

    - name: get_snow_service2
      type: http
      with:
        headers:
          Authorization: '{{ consts.snow_auth }}'
          Accept: application/json
        method: GET
        url: '{{ consts.snow_host }}/api/now/table/cmdb_ci_service_auto/{{steps.get_snow_service.output.data.result.services[0].sys_id}}'
      on-failure:
        continue: true
    - name: get_snow_service3
      type: http
      with:
        headers:
          Authorization: '{{ consts.snow_auth }}'
          Accept: application/json
        method: GET
        url: '{{ steps.get_snow_service2.output.data.result.owned_by.link}}'
      on-failure:
        continue: true
    - name: get_snow_service4
      type: http
      with:
        headers:
          Authorization: '{{ consts.snow_auth }}'
          Accept: application/json
        method: GET
        url: '{{ steps.get_snow_service2.output.data.result.support_group.link}}'
      on-failure:
        continue: true
    - name: store_cmdb_service
      type: http
      with:
        body: |
          {
            "service.environment" : "{{ steps.foreach_environment.item }}", 
            "service.name" : "{{ foreach.item['service.name']}}"
            {% if steps.get_snow_service.output.data.result.services.size > 0 %}
            ,"cmdb_owner": "{{ steps.get_snow_service3.output.data.result.user_name}}",
            "cmdb_support_group": "{{ steps.get_snow_service4.output.data.result.name}}",
            "cmdb_id": "{{ steps.get_snow_service.output.data.result.services[0].number}}"
            {% endif %}
          }
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
        method: PUT
        timeout: 30s
        url: "{{ consts.es_host }}/workflow_cmdb/_doc/{{ foreach.item['service.name']}}"

  - name: host_names
    type: http
    with:
      body:
        query: |
          FROM traces-*
          | WHERE @timestamp >= "{{ steps.get_start_time.output.data.values[0] }}" AND @timestamp <= "{{ steps.get_end_time.output.data.values[0] }}"
          {% if foreach.item != 'ENVIRONMENT_NOT_DEFINED' %}
          | WHERE service.environment == "{{ foreach.item }}"
          {% endif %}
          | WHERE service.name IS NOT NULL AND host.name IS NOT NULL
          | STATS count = COUNT() BY service.name, host.name, k8s.namespace.name
          | KEEP service.name, host.name, k8s.namespace.name
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: POST
      url: '{{ consts.es_host }}/_query?format=txt'

  - name: get_topology1
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        persist: false
        instructions:
        - Output a field 'topology' which is a JSON object in node-link format.
        messages:
        - '@timestamp': now
          message:
            content: |
              Build a topology for the attached Service Map.
              # Service Map
              ```
              {{ steps.get_service_map.output.data | json }}
              ```
              For each node in the topology, use the attached Service/Host Lookup Table to add an additional field 'host.name' which is the hostname of the VM or kubernetes node or machine on which the service is running and 'k8s.namespace.name' which is the kubernetes namespace on which the service is running.
              # Service/Host Lookup Table
              ```
              {{ steps.host_names.output.data }}
              ```
            role: user
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'

  - name: store_topology
    type: http
    with:
      body: '{"system":"{{ foreach.item }}", "topology": {{ steps.get_topology1.output.data.result.topology | json }} }'
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: POST
      timeout: 30s
      url: '{{ consts.es_host }}/workflow_topology/_doc'
