apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remote-role
  namespace: $NAMESPACE
rules:
- apiGroups: ["apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-account
  namespace: $NAMESPACE
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remote-binding
  namespace: $NAMESPACE
subjects:
- kind: ServiceAccount
  name: remote-account
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: remote-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote
  namespace: $NAMESPACE
  labels:
    app: trading
    service: remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: remote
  template:
    metadata:
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
      labels:
        app: trading
        service: remote
    spec:
      serviceAccountName: remote-account
      containers:
        - name: remote
          image: $REPO/remote:$COURSE
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "$NAMESPACE"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: remote
  name: remote-ext
  namespace: $NAMESPACE
spec:
  ports:
    - name: remote
      port: 43210
      targetPort: 10000
  type: LoadBalancer
  selector:
    app: trading
    service: remote
---